# Generated by Django 3.2 on 2023-02-03 13:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Blog Category',
            },
        ),
        migrations.CreateModel(
            name='Blogs_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=2000)),
                ('Image', models.ImageField(upload_to='blog')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_category')),
            ],
            options={
                'verbose_name_plural': 'Blog Table',
            },
        ),
    ]
