# Generated by Django 3.2 on 2023-02-03 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs_table',
            old_name='Details',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='blogs_table',
            name='Image',
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='Read_Time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='Short_Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 3, 19, 32, 30, 955585)),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Article_images/'),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='slug',
            field=models.SlugField(default='Auto-Generate', editable=False),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogs_table',
            name='total_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogs_table',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
