# Generated by Django 3.2 on 2023-02-03 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20230203_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 0, 38, 45, 58910)),
        ),
        migrations.AlterField(
            model_name='blogs_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blog_images/'),
        ),
    ]
