# Generated by Django 3.2 on 2023-02-11 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 13, 7, 23, 261271)),
        ),
    ]
