# Generated by Django 3.2 on 2023-02-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Table',
            },
        ),
        migrations.AlterModelOptions(
            name='contact_form',
            options={'verbose_name_plural': 'Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='portfolio_category',
            options={'verbose_name_plural': 'Portfolio Category'},
        ),
        migrations.AlterModelOptions(
            name='portfolio_details',
            options={'verbose_name_plural': 'Portfolio Details'},
        ),
    ]
