# Generated by Django 3.2 on 2023-02-03 18:38

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product_images/')),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 0, 38, 45, 61875))),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_category')),
            ],
            options={
                'verbose_name_plural': 'Product Table',
            },
        ),
    ]
