# Generated by Django 3.2 on 2023-02-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230204_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 11, 39, 4, 582701)),
        ),
    ]
