# Generated by Django 3.2 on 2023-02-11 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 13, 7, 23, 263764)),
        ),
    ]
